{
 "title": "Fail2ban",
 "description": "Add fail2ban graph for ssh, purftp, dovecot, postfix",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "ALL hypervisor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "banned.mean",
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" }
     ]
    },
    {
     "alias": "failed.mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" }
     ]
    }
   ]
  },
  {
   "title": "ALL srv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "banned.mean",
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" }
     ]
    },
    {
     "alias": "failed.mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" }
     ]
    }
   ]
  },
  {
   "title": "SSH hypervisor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" },
      { "condition": "AND", "key": "jail", "operator": "=", "value": "sshd" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" }
     ]
    }
   ]
  },
  {
   "title": "SSH srv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" },
      { "condition": "AND", "key": "jail", "operator": "=", "value": "sshd" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" }
     ]
    }
   ]
  },
  {
   "title": "Apache hypervisor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" },
      { "condition": "AND", "key": "jail", "operator": "=", "value": "apache-auth" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "hypervisor.sofia" }
     ]
    }
   ]
  },
  {
   "title": "Apache hypervisor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fail2ban_sshd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "banned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" },
      { "condition": "AND", "key": "jail", "operator": "=", "value": "apache-auth" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fail2ban",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "u-srv.sofia" }
     ]
    }
   ]
  },
  {
   "title": "PureFTP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fail2ban_pureftpd", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Dovecot pop3imap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fail2ban_dovecot_pop3imap", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Postfix sasl",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fail2ban_postfix_sasl", "legendFormat": "{{type}}" }
   ]
  }
 ]
}